.PHONY: clean cleaner

all:
	python3 ../support/tutorial_tools/notebook/process_notebook.py emseqfinder

clean:
	rm -f emseqfinder.md Doxyfile
	rm -rf html

cleaner:
	rm -f emseqfinder.ipynb emseqfinder-colab.ipynb emseqfinder.py emseqfinder.md Doxyfile
	rm -rf html

